import os
import subprocess
import math
from pathlib import Path

import pytest
import numpy as np

from hanajit import jit, UnsupportedError
from hanajit.backends import executable


pytestmark = pytest.mark.skipif(
    not executable._x86_64(),
    reason="standalone executable integration tests require x86-64",
)


def _run_if_linked(out, *args):
    if out.executable is None:
        return None
    r = subprocess.run([out.executable, *map(str, args)],
                       capture_output=True, text=True, timeout=20)
    assert r.returncode == 0, r.stderr
    return r.stdout.strip()


def test_scalar_executable_artifacts_and_execution(tmp_path):
    @jit(signature="i64, i64")
    def add_mul(a, b):
        return a * 3 + b

    out = add_mul.export_executable(tmp_path / "add_mul")
    assert Path(out.object).is_file()
    assert Path(out.object).stat().st_size > 0
    assert Path(out.source).is_file()
    assert Path(out.build).is_file()
    assert out.ptx is None
    source = Path(out.source).read_text(encoding="utf-8")
    assert "static int64_t hj_cpu_kernel(int64_t hj_v0, int64_t hj_v1)" in source
    assert "strtoll" in source
    assert "Python.h" not in source
    assert "hanajit" not in source.lower().replace(
        "generated by hanajit.export_executable", "")
    got = _run_if_linked(out, 7, -2)
    if got is not None:
        assert got == "19"


def test_float_and_bool_cli_contract(tmp_path):
    @jit(signature="f64, bool")
    def choose(x, enabled):
        return x * 2.0 if enabled else -x

    out = choose.export_executable(tmp_path / "choose")
    got = _run_if_linked(out, 1.25, 1)
    if got is not None:
        assert float(got) == pytest.approx(2.5)
        bad = subprocess.run([out.executable, "1.25", "yes"],
                             capture_output=True, text=True, timeout=20)
        assert bad.returncode == 64
        assert "invalid argument 2" in bad.stderr


def test_export_with_signature_needs_no_prior_call(tmp_path):
    @jit
    def square(x):
        return x * x

    out = square.export_executable(tmp_path / "square", sig="i64")
    assert Path(out.object).exists()
    got = _run_if_linked(out, 12)
    if got is not None:
        assert got == "144"


@pytest.mark.parametrize("a,b", [(-17, 5), (17, -5), (-17, -5), (17, 5)])
def test_executable_python_divmod_semantics(tmp_path, a, b):
    @jit(signature="i64, i64")
    def divmod_mix(x, y):
        return (x // y) * 101 + (x % y)

    out = divmod_mix.export_executable(tmp_path / f"divmod_{a}_{b}")
    got = _run_if_linked(out, a, b)
    if got is not None:
        assert int(got) == divmod_mix.__wrapped__(a, b)


def test_executable_loops_control_flow_and_recursion(tmp_path):
    @jit(signature="i64")
    def loop(n):
        acc = 0
        for i in range(-3, n, 2):
            if i % 5 == 0:
                continue
            acc += i * i
        return acc

    @jit(signature="i64")
    def fib(n):
        if n < 2:
            return n
        return fib(n - 1) + fib(n - 2)

    loop_out = loop.export_executable(tmp_path / "loop")
    fib_out = fib.export_executable(tmp_path / "fib")
    got = _run_if_linked(loop_out, 31)
    if got is not None:
        assert int(got) == loop.__wrapped__(31)
    got = _run_if_linked(fib_out, 20)
    if got is not None:
        assert int(got) == 6765


def test_executable_math_and_i64_wraparound(tmp_path):
    @jit(signature="f64")
    def wave(x):
        return math.sin(x) + math.sqrt(abs(x)) + math.pi

    @jit(signature="i64")
    def wrap(x):
        return x + 1

    wave_out = wave.export_executable(tmp_path / "wave")
    wrap_out = wrap.export_executable(tmp_path / "wrap")
    got = _run_if_linked(wave_out, 2.25)
    if got is not None:
        assert float(got) == pytest.approx(wave.__wrapped__(2.25), rel=1e-14)
    got = _run_if_linked(wrap_out, 2**63 - 1)
    if got is not None:
        assert int(got) == -(2**63)


def test_pointer_cli_rejected_clearly(tmp_path):
    @jit(signature="f64*, i64")
    def total(x, n):
        acc = 0.0
        for i in range(n):
            acc += x[i]
        return acc

    with pytest.raises(UnsupportedError, match="scalar signatures only"):
        total.export_executable(tmp_path / "total")


def test_dynamic_python_feature_rejected_not_bundled(tmp_path):
    @jit
    def dynamic(x):
        return eval("x + 1")

    with pytest.raises(UnsupportedError, match="only abs/int/float"):
        dynamic.export_executable(tmp_path / "dynamic", sig="i64")


def test_cuda_optional_embeds_ptx_and_cpu_fallback(tmp_path):
    @jit(signature="f64, f64")
    def affine(x, y):
        return x * 2.0 + y

    out = affine.export_executable(tmp_path / "affine",
                                   cuda="optional")
    assert out.ptx is not None
    ptx = Path(out.ptx).read_text(encoding="utf-8")
    source = Path(out.source).read_text(encoding="utf-8")
    assert "__hanajit_cuda_affine" in ptx
    assert "hj_embedded_ptx" in source
    assert "nvcuda.dll" in source
    assert "libcuda.so.1" in source
    assert "result = hj_cpu_kernel(a0, a1)" in source  # CPU fallback embedded
    got = _run_if_linked(out, 1.5, 4.0)
    if got is not None:
        assert float(got) == pytest.approx(7.0)


def test_cuda_boolean_result_uses_stable_device_abi(tmp_path):
    @jit(signature="i64")
    def is_positive(x):
        return x > 0

    out = is_positive.export_executable(tmp_path / "is_positive",
                                         cuda="optional")
    source = Path(out.source).read_text(encoding="utf-8")
    assert "int64_t hj_cuda_bool_result" in source
    assert "*out = hj_cuda_bool_result != 0" in source
    got = _run_if_linked(out, -3)
    if got is not None:
        assert got == "0"
    got = _run_if_linked(out, 3)
    if got is not None:
        assert got == "1"


def test_cuda_required_has_no_runtime_cpu_fallback(tmp_path):
    @jit(signature="i64")
    def inc(x):
        return x + 1

    out = inc.export_executable(tmp_path / "inc", cuda="required")
    source = Path(out.source).read_text(encoding="utf-8")
    assert "if (1)" in source
    assert "CUDA execution required" in source
    if out.executable is not None:
        from hanajit.backends import rt
        r = subprocess.run([out.executable, "41"], capture_output=True,
                           text=True, timeout=20)
        if rt.get_runtime("cuda") is not None:
            assert r.returncode == 0, r.stderr
            assert r.stdout.strip() == "42"
        else:
            assert r.returncode == 70
            assert "CUDA execution required" in r.stderr


def test_cuda_recursive_kernel_rejected(tmp_path):
    @jit(signature="i64")
    def fib(n):
        if n < 2:
            return n
        return fib(n - 1) + fib(n - 2)

    with pytest.raises(UnsupportedError, match="recursive kernels"):
        fib.export_executable(tmp_path / "fib", cuda="optional")


def test_bad_cuda_mode(tmp_path):
    @jit(signature="i64")
    def ident(x):
        return x

    with pytest.raises(ValueError, match="cuda must be"):
        ident.export_executable(tmp_path / "ident", cuda="sometimes")


def test_x86_only_guard(tmp_path, monkeypatch):
    @jit(signature="i64")
    def ident(x):
        return x

    monkeypatch.setattr(executable, "_x86_64", lambda: False)
    with pytest.raises(UnsupportedError, match="require x86-64"):
        ident.export_executable(tmp_path / "ident")


def test_zero_argument_executable(tmp_path):
    @jit(native_dispatch=False)
    def answer():
        return 42

    out = answer.export_executable(tmp_path / "answer", sig=())
    got = _run_if_linked(out)
    if got is not None:
        assert got == "42"


def test_cli_arity_and_i64_parser_failures(tmp_path):
    @jit(signature="i64")
    def identity(x):
        return x

    out = identity.export_executable(tmp_path / "parse_i64")
    if out.executable is None:
        return

    for args in ([], ["1", "2"]):
        r = subprocess.run([out.executable, *args], capture_output=True,
                           text=True, timeout=20)
        assert r.returncode == 64
        assert "usage:" in r.stderr
    for value in ("12x", "", str(2**63), str(-(2**63) - 1)):
        r = subprocess.run([out.executable, value], capture_output=True,
                           text=True, timeout=20)
        assert r.returncode == 64
        assert "invalid argument 1" in r.stderr


def test_f64_parser_and_special_values(tmp_path):
    @jit(signature="f64")
    def identity(x):
        return x

    out = identity.export_executable(tmp_path / "parse_f64")
    if out.executable is None:
        return

    for value, expected in (("1.25e2", 125.0), ("inf", math.inf),
                            ("-inf", -math.inf)):
        got = _run_if_linked(out, value)
        assert float(got) == expected
    assert math.isnan(float(_run_if_linked(out, "nan")))
    for value in ("1.2x", "1e9999", ""):
        r = subprocess.run([out.executable, value], capture_output=True,
                           text=True, timeout=20)
        assert r.returncode == 64
        assert "invalid argument 1" in r.stderr


def test_integer_bitwise_shift_and_unary_semantics(tmp_path):
    @jit(signature="i64, i64")
    def integer_ops(a, b):
        mixed = (a & b) ^ (a | b)
        shifted = (a << 3) + (b >> 2)
        return +mixed - shifted + abs(-b)

    out = integer_ops.export_executable(tmp_path / "integer_ops")
    for a, b in ((23, 9), (-23, 9), (123456, -311)):
        got = _run_if_linked(out, a, b)
        if got is not None:
            assert int(got) == integer_ops.__wrapped__(a, b)


def test_while_break_continue_and_pass_semantics(tmp_path):
    @jit(signature="i64")
    def scan(n):
        i = 0
        total = 0
        while i < n:
            i += 1
            if i % 7 == 0:
                continue
            if i > 40:
                break
            pass
            total += i * 3
        return total

    out = scan.export_executable(tmp_path / "scan")
    for n in (0, 6, 30, 100):
        got = _run_if_linked(out, n)
        if got is not None:
            assert int(got) == scan.__wrapped__(n)


def test_all_range_arities_and_negative_step(tmp_path):
    @jit(signature="i64")
    def ranges(n):
        total = 0
        for i in range(n):
            total += i
        for i in range(2, n):
            total += i * 2
        for i in range(n, -5, -3):
            total -= i
        return total

    out = ranges.export_executable(tmp_path / "ranges")
    for n in (0, 1, 9, 31):
        got = _run_if_linked(out, n)
        if got is not None:
            assert int(got) == ranges.__wrapped__(n)


def test_float_div_floor_mod_and_power_semantics(tmp_path):
    @jit(signature="f64, f64")
    def float_ops(a, b):
        return a / b + a // b + a % b + (abs(a) ** 1.5)

    out = float_ops.export_executable(tmp_path / "float_ops")
    for a, b in ((7.5, 2.0), (-7.5, 2.0), (7.5, -2.0), (-7.5, -2.0)):
        got = _run_if_linked(out, a, b)
        if got is not None:
            assert float(got) == pytest.approx(
                float_ops.__wrapped__(a, b), rel=1e-13)


def test_all_supported_scalar_math_functions(tmp_path):
    @jit(signature="f64")
    def math_ops(x):
        a = abs(x) + 1.25
        return (math.sqrt(a) + math.exp(x / 10.0) + math.log(a) +
                math.sin(x) + math.cos(x) + math.floor(x) +
                math.ceil(x) + math.pow(a, 1.5) + math.fabs(x) +
                math.e + math.pi)

    out = math_ops.export_executable(tmp_path / "math_ops")
    for x in (-2.25, 0.0, 3.75):
        got = _run_if_linked(out, x)
        if got is not None:
            assert float(got) == pytest.approx(
                math_ops.__wrapped__(x), rel=1e-13)


def test_supported_numpy_scalar_calls_do_not_bundle_numpy(tmp_path):
    @jit(signature="f64")
    def numpy_scalar(x):
        return np.sin(x) + np.cos(x) + np.sqrt(abs(x)) + np.pi

    out = numpy_scalar.export_executable(tmp_path / "numpy_scalar")
    source = Path(out.source).read_text(encoding="utf-8")
    assert "numpy" not in source.lower()
    assert "Python.h" not in source
    got = _run_if_linked(out, 1.75)
    if got is not None:
        assert float(got) == pytest.approx(
            numpy_scalar.__wrapped__(1.75), rel=1e-13)


def test_integer_comparison_matrix(tmp_path):
    @jit(signature="i64, i64")
    def comparisons(a, b):
        result = 0
        if a == b:
            result += 1
        if a != b:
            result += 2
        if a < b:
            result += 4
        if a <= b:
            result += 8
        if a > b:
            result += 16
        if a >= b:
            result += 32
        return result

    out = comparisons.export_executable(tmp_path / "icmp")
    for a, b in ((1, 1), (-2, 5), (9, -4)):
        got = _run_if_linked(out, a, b)
        if got is not None:
            assert int(got) == comparisons.__wrapped__(a, b)


def test_float_comparisons_are_ordered_including_nan(tmp_path):
    @jit(signature="f64, f64")
    def comparisons(a, b):
        result = 0
        if a == b:
            result += 1
        if a != b:
            result += 2
        if a < b:
            result += 4
        if a <= b:
            result += 8
        if a > b:
            result += 16
        if a >= b:
            result += 32
        return result

    out = comparisons.export_executable(tmp_path / "fcmp")
    for a, b in ((1.0, 1.0), (-2.0, 5.0), (9.0, -4.0)):
        got = _run_if_linked(out, a, b)
        if got is not None:
            assert int(got) == comparisons.__wrapped__(a, b)
    got = _run_if_linked(out, "nan", 1.0)
    if got is not None:
        assert got == "0"  # LLVM/HanaJit ordered comparison contract


def test_bool_arguments_not_and_or_and_ternary(tmp_path):
    @jit(signature="bool, bool, i64")
    def logic(a, b, x):
        combined = (a and b) or not x
        return 10 if combined else -10

    out = logic.export_executable(tmp_path / "logic")
    for a, b, x in ((0, 0, 0), (1, 0, 3), (1, 1, 3), (0, 1, -2)):
        got = _run_if_linked(out, a, b, x)
        if got is not None:
            assert int(got) == logic.__wrapped__(bool(a), bool(b), x)


def test_output_path_with_spaces_and_build_script_rebuild(tmp_path):
    @jit(signature="i64")
    def double(x):
        return x * 2

    out = double.export_executable(tmp_path / "directory with spaces" /
                                   "double tool")
    got = _run_if_linked(out, 21)
    if got is None:
        return
    assert got == "42"
    if os.name == "nt":
        command = ["cmd.exe", "/d", "/c", out.build]
    else:
        command = ["/bin/sh", out.build]
    rebuilt = subprocess.run(command, capture_output=True, text=True,
                             timeout=120)
    assert rebuilt.returncode == 0, rebuilt.stderr or rebuilt.stdout
    assert _run_if_linked(out, 8) == "16"


def test_cpu_executable_runs_without_python_environment(tmp_path):
    @jit(signature="i64")
    def increment(x):
        return x + 1

    out = increment.export_executable(tmp_path / "empty_env")
    if out.executable is None:
        return
    env = {}
    if os.name == "nt":
        # CPython 3.10 cannot pass a completely empty environment block to
        # CreateProcess.  SystemRoot is enough for Windows while still
        # proving that the executable needs no Python/HanaJit environment.
        env["SystemRoot"] = os.environ["SystemRoot"]
    r = subprocess.run([out.executable, "41"], capture_output=True,
                       text=True, timeout=20, env=env)
    assert r.returncode == 0, r.stderr
    assert r.stdout.strip() == "42"


def test_cuda_optional_bool_argument_and_result(tmp_path):
    @jit(signature="bool, i64")
    def gated_positive(enabled, x):
        return enabled and x > 0

    out = gated_positive.export_executable(tmp_path / "gated_positive",
                                            cuda="optional")
    for enabled, x, expected in ((0, 4, "0"), (1, -4, "0"),
                                 (1, 4, "1")):
        got = _run_if_linked(out, enabled, x)
        if got is not None:
            assert got == expected
