"""FPGA backend (experimental).

There is no direct LLVM->bitstream path; FPGA flows go through
High-Level Synthesis (HLS). Two practical routes from our IR:

1. LLVM IR -> Vitis HLS: AMD/Xilinx Vitis HLS is itself LLVM-based and
   accepts LLVM IR through its front-end flow (inject .ll into the
   hls compilation, or use the open-source Vitis HLS LLVM fork).
2. LLVM IR -> CIRCT: the LLVM CIRCT project (circt.llvm.org) lowers to
   hardware dialects (Calyx/FIRRTL) and emits Verilog.

`export_for_hls` writes a full Vitis HLS project kit:

    <prefix>.ll         self-contained annotated LLVM IR (CIRCT / IR flow)
    <prefix>_hls.cpp    synthesizable C++ top function with HLS pragmas,
                        transpiled from the typed Python AST (like the
                        metal backend transpiles to MSL)
    <prefix>_tb.cpp     C simulation testbench (csim_design)
    <prefix>_hls.tcl    runnable Vitis HLS script (csim -> csynth ->
                        export_design), part and clock parameterizable

The C++ source is the turnkey route — Vitis HLS synthesizes it directly,
no LLVM front-end injection needed. The .ll remains for IR-level flows.
Iqbal-note: this pairs naturally with the existing FPGA acceleration
work — the transpiled top function is plain scalar compute with the
pipelining pragmas already in place.
"""
import ast
import textwrap
from collections import namedtuple

from ..errors import UnsupportedError
from ..typeinfer import (I64, F64, BOOL, PF64, PI64, GPU_INTRINSICS,
                         MATH_FNS, MATH_MODULES)

# Vitis HLS synthesizes double natively (mapped to DSP blocks), so f64
# stays 64-bit here, unlike the metal backend's float lowering.
HLSTY = {I64: "long long", F64: "double", BOOL: "bool",
         PF64: "double *", PI64: "long long *"}
SCALAR = {I64: "long long", F64: "double", BOOL: "bool"}
PRINTF_FMT = {I64: "%lld", F64: "%f", BOOL: "%d"}

DEFAULT_PART = "xcu250-figd2104-2L-e"
DEFAULT_CLOCK_NS = 3.3

HEADER = """\
// Generated by hanajit (export_fpga) — synthesizable Vitis HLS C++.
// NOTE: integer / and % use C truncation semantics in hardware, not
// Python floor semantics (differs for negative operands).
#include <cmath>

"""

FpgaExport = namedtuple("FpgaExport", "ll tcl cpp tb")


class HLSCppGen:
    """Transpile the typed Python AST to a Vitis HLS C++ top function.

    Mirrors the metal backend's MSLGen; differences: the function returns
    its value (HLS tops are not void kernels), interface pragmas replace
    buffer attributes, and innermost loops get a PIPELINE pragma.
    """

    def __init__(self, func_ast, arg_types, var_types, ret_type):
        self.f = func_ast
        self.arg_types = arg_types
        self.var_types = var_types
        self.ret_type = ret_type
        self.out = []
        self.depth = 1
        if any(isinstance(n, ast.Call) and isinstance(n.func, ast.Name)
               and n.func.id in GPU_INTRINSICS for n in ast.walk(func_ast)):
            raise UnsupportedError(
                "fpga: GPU thread intrinsics have no HLS equivalent — "
                "write the loop explicitly")

    def line(self, s):
        self.out.append("    " * self.depth + s)

    def generate(self):
        params = []
        for a in self.f.args.args:
            ty = self.arg_types[a.arg]
            if ty not in HLSTY:
                raise UnsupportedError(
                    f"fpga: array argument {a.arg!r} ({ty}) — use a raw "
                    "pointer type in signature= ('f64*'/'i64*')")
            params.append(f"{HLSTY[ty]}{'' if ty in (PF64, PI64) else ' '}"
                          f"{a.arg}")
        sig = (f'extern "C" {SCALAR[self.ret_type]} {self.f.name}('
               + ", ".join(params) + ")")

        # interface pragmas: pointers -> AXI master ports, scalars and the
        # return value -> the AXI-lite control bundle
        for a in self.f.args.args:
            ty = self.arg_types[a.arg]
            if ty in (PF64, PI64):
                self.line(f"#pragma HLS INTERFACE m_axi port={a.arg} "
                          "offset=slave bundle=gmem")
            self.line(f"#pragma HLS INTERFACE s_axilite port={a.arg}")
        self.line("#pragma HLS INTERFACE s_axilite port=return")
        self.line("")

        # declare locals (params excluded) up front
        for name, ty in sorted(self.var_types.items()):
            if name in self.arg_types:
                continue
            if ty not in SCALAR:
                raise UnsupportedError(
                    f"fpga: unsupported local type {ty} for {name!r}")
            zero = "false" if ty == BOOL else ("0.0" if ty == F64 else "0")
            self.line(f"{SCALAR[ty]} {name} = {zero};")
        for stmt in self.f.body:
            self.stmt(stmt)
        body = "\n".join(self.out)
        return HEADER + sig + " {\n" + body + "\n}\n"

    @staticmethod
    def _is_innermost(node):
        return not any(isinstance(n, (ast.For, ast.While))
                       for n in ast.walk(node)
                       if n is not node)

    def _loop_body(self, node):
        self.depth += 1
        if self._is_innermost(node):
            self.line("#pragma HLS PIPELINE II=1")
        for s in node.body:
            self.stmt(s)
        self.depth -= 1
        self.line("}")

    # ------------------------------ statements ------------------------------
    def stmt(self, node):
        m = getattr(self, "s_" + type(node).__name__, None)
        if m is None:
            raise UnsupportedError(
                f"fpga: unsupported statement {type(node).__name__}")
        m(node)

    def s_Assign(self, node):
        t = node.targets[0]
        if isinstance(t, ast.Subscript):
            self.line(f"{self.expr(t.value)}[{self.expr(t.slice)}] = "
                      f"{self.expr(node.value)};")
        else:
            self.line(f"{t.id} = {self.expr(node.value)};")

    def s_AugAssign(self, node):
        op = {ast.Add: "+", ast.Sub: "-", ast.Mult: "*", ast.Div: "/",
              ast.Mod: "%", ast.FloorDiv: "/", ast.BitAnd: "&",
              ast.BitOr: "|", ast.BitXor: "^", ast.LShift: "<<",
              ast.RShift: ">>"}.get(type(node.op))
        if op is None:
            raise UnsupportedError("fpga: unsupported augmented op")
        self.line(f"{node.target.id} {op}= {self.expr(node.value)};")

    def s_Return(self, node):
        if node.value is None:
            raise UnsupportedError("fpga: bare return in a typed kernel")
        self.line(f"return {self.expr(node.value)};")

    def s_Expr(self, node):
        pass

    def s_Pass(self, node):
        pass

    def s_Break(self, node):
        self.line("break;")

    def s_Continue(self, node):
        self.line("continue;")

    def s_If(self, node):
        self.line(f"if ({self.expr(node.test)}) {{")
        self.depth += 1
        for s in node.body:
            self.stmt(s)
        self.depth -= 1
        if node.orelse:
            self.line("} else {")
            self.depth += 1
            for s in node.orelse:
                self.stmt(s)
            self.depth -= 1
        self.line("}")

    def s_While(self, node):
        self.line(f"while ({self.expr(node.test)}) {{")
        self._loop_body(node)

    def s_For(self, node):
        v = node.target.id
        a = [self.expr(x) for x in node.iter.args]
        if len(a) == 1:
            start, stop, step = "0", a[0], "1"
        elif len(a) == 2:
            start, stop, step = a[0], a[1], "1"
        else:
            start, stop, step = a
        cond = (f"({step}) > 0 ? ({v} < ({stop})) : ({v} > ({stop}))"
                if step not in ("1",) else f"{v} < ({stop})")
        self.line(f"for ({v} = {start}; {cond}; {v} += {step}) {{")
        self._loop_body(node)

    # ----------------------------- expressions ------------------------------
    def expr(self, node):
        if isinstance(node, ast.Constant):
            if isinstance(node.value, bool):
                return "true" if node.value else "false"
            if isinstance(node.value, float):
                return f"{node.value!r}"
            return str(node.value)
        if isinstance(node, ast.Name):
            return node.id
        if isinstance(node, ast.Subscript):
            return f"{self.expr(node.value)}[{self.expr(node.slice)}]"
        if isinstance(node, ast.UnaryOp):
            op = {ast.USub: "-", ast.UAdd: "+", ast.Not: "!"}[type(node.op)]
            return f"({op}{self.expr(node.operand)})"
        if isinstance(node, ast.BinOp):
            if isinstance(node.op, ast.Div):
                return (f"((double)({self.expr(node.left)}) / "
                        f"(double)({self.expr(node.right)}))")
            if isinstance(node.op, ast.Pow):
                return (f"pow((double)({self.expr(node.left)}), "
                        f"(double)({self.expr(node.right)}))")
            op = {ast.Add: "+", ast.Sub: "-", ast.Mult: "*",
                  ast.FloorDiv: "/", ast.Mod: "%", ast.BitAnd: "&",
                  ast.BitOr: "|", ast.BitXor: "^", ast.LShift: "<<",
                  ast.RShift: ">>"}.get(type(node.op))
            if op is None:
                raise UnsupportedError("fpga: unsupported operator")
            return f"({self.expr(node.left)} {op} {self.expr(node.right)})"
        if isinstance(node, ast.Compare):
            op = {ast.Eq: "==", ast.NotEq: "!=", ast.Lt: "<", ast.LtE: "<=",
                  ast.Gt: ">", ast.GtE: ">="}[type(node.ops[0])]
            return (f"({self.expr(node.left)} {op} "
                    f"{self.expr(node.comparators[0])})")
        if isinstance(node, ast.BoolOp):
            op = " && " if isinstance(node.op, ast.And) else " || "
            return "(" + op.join(self.expr(v) for v in node.values) + ")"
        if isinstance(node, ast.IfExp):
            return (f"({self.expr(node.test)} ? {self.expr(node.body)} : "
                    f"{self.expr(node.orelse)})")
        if (isinstance(node, ast.Call) and isinstance(node.func, ast.Attribute)
                and isinstance(node.func.value, ast.Name)
                and node.func.value.id in MATH_MODULES
                and node.func.attr in MATH_FNS):
            inner = ", ".join(f"(double)({self.expr(a)})" for a in node.args)
            return f"{node.func.attr}({inner})"
        if isinstance(node, ast.Call) and isinstance(node.func, ast.Name):
            fn = node.func.id
            if fn == "abs":
                return f"std::abs({self.expr(node.args[0])})"
            if fn == "float":
                return f"(double)({self.expr(node.args[0])})"
            if fn == "int":
                return f"(long long)({self.expr(node.args[0])})"
        raise UnsupportedError(
            f"fpga: unsupported expression {type(node).__name__}")


def transpile(func_ast, arg_types, var_types, ret_type):
    return HLSCppGen(func_ast, arg_types, var_types, ret_type).generate()


def _testbench(func_name, func_ast, arg_types, ret_type):
    """C simulation harness: fills buffers, calls the top, prints result."""
    decls, args = [], []
    for a in func_ast.args.args:
        ty = arg_types[a.arg]
        if ty in (PF64, PI64):
            ety = "double" if ty == PF64 else "long long"
            init = "0.5 * i" if ty == PF64 else "i"
            decls.append(f"    static {ety} {a.arg}[N];\n"
                         f"    for (int i = 0; i < N; i++) "
                         f"{a.arg}[i] = {init};")
            args.append(a.arg)
        else:
            val = {I64: "4", F64: "1.5", BOOL: "true"}[ty]
            decls.append(f"    {SCALAR[ty]} {a.arg} = {val};")
            args.append(a.arg)
    fmt = PRINTF_FMT[ret_type]
    cast = "(double)" if ret_type == F64 else ""
    body = "\n".join(decls)
    proto = ", ".join(HLSTY[arg_types[a.arg]] for a in func_ast.args.args)
    return textwrap.dedent(f"""\
        // Generated by hanajit — C simulation testbench for {func_name}
        // (csim_design). Adjust N and the fill values to your workload.
        #include <cstdio>

        extern "C" {SCALAR[ret_type]} {func_name}({proto});

        int main() {{
            const int N = 256;
            (void)N;
        {body}
            {SCALAR[ret_type]} r = {func_name}({", ".join(args)});
            printf("{func_name} -> {fmt}\\n", {cast}r);
            return 0;
        }}
        """)


def _tcl(func_name, prefix_base, has_cpp, part, clock_ns):
    if has_cpp:
        return textwrap.dedent(f"""\
            # Vitis HLS flow for {func_name} — generated by hanajit.
            # Run with:  vitis_hls -f {prefix_base}_hls.tcl
            open_project {func_name}_prj
            set_top {func_name}
            add_files {prefix_base}_hls.cpp
            add_files -tb {prefix_base}_tb.cpp
            open_solution sol1
            set_part {part}
            create_clock -period {clock_ns}
            csim_design
            csynth_design
            # cosim_design   ;# RTL/C co-simulation (slow; enable as needed)
            export_design -format ip_catalog
            """)
    return textwrap.dedent(f"""\
        # Vitis HLS flow stub for {func_name} — generated by hanajit.
        # No C++ source was generated for this kernel; inject the LLVM IR
        # via the Vitis HLS LLVM front-end flow instead:
        #   https://github.com/Xilinx/HLS
        open_project {func_name}_prj
        set_top {func_name}
        open_solution sol1
        set_part {part}
        create_clock -period {clock_ns}
        csynth_design
        export_design -format ip_catalog
        """)


def export_for_hls(module, func_name, path_prefix, func_ast=None,
                   arg_types=None, var_types=None, ret_type=None,
                   part=DEFAULT_PART, clock_ns=DEFAULT_CLOCK_NS):
    """Write the HLS project kit for `func_name` next to `path_prefix`.

    Returns an FpgaExport namedtuple of paths. The C++ source and
    testbench need the typed AST (func_ast/arg_types/var_types/ret_type);
    without it — or when the kernel uses constructs the transpiler does
    not cover — they are None and only the IR + TCL stub are written.
    """
    import os
    ll_path = f"{path_prefix}.ll"
    tcl_path = f"{path_prefix}_hls.tcl"
    cpp_path = tb_path = None
    with open(ll_path, "w", encoding="utf-8") as f:
        f.write(str(module))
    if func_ast is not None:
        try:
            cpp = transpile(func_ast, arg_types, var_types, ret_type)
            tb = _testbench(func_name, func_ast, arg_types, ret_type)
            cpp_path = f"{path_prefix}_hls.cpp"
            tb_path = f"{path_prefix}_tb.cpp"
            with open(cpp_path, "w", encoding="utf-8") as f:
                f.write(cpp)
            with open(tb_path, "w", encoding="utf-8") as f:
                f.write(tb)
        except UnsupportedError:
            cpp_path = tb_path = None  # IR + TCL stub still useful
    prefix_base = os.path.basename(path_prefix)
    with open(tcl_path, "w", encoding="utf-8") as f:
        f.write(_tcl(func_name, prefix_base, cpp_path is not None,
                     part, clock_ns))
    return FpgaExport(ll_path, tcl_path, cpp_path, tb_path)
