"""Apple GPU backend: transpile the typed Python AST to Metal Shading
Language (MSL) source.

LLVM has no Metal target (Apple's AIR bitcode is a private LLVM fork), so
unlike cuda/amd/intel this backend emits compilable .metal source instead
of retargeted IR. The compile subset is small enough that source-level
transpilation is exact.

Semantics caveats (stated in the generated header):
- Metal has no double: f64 lowers to 32-bit `float` (precision differs).
- Integer / and % follow C truncation semantics on the GPU, not Python
  floor semantics.

Thread intrinsics map as:
    thread_id()  -> thread_position_in_threadgroup
    block_id()   -> threadgroup_position_in_grid
    block_dim()  -> threads_per_threadgroup

Validate on a Mac with:  xcrun -sdk macosx metal -c kernel.metal
(see examples/metal_check.py).
"""
import ast
from ..errors import UnsupportedError
from ..typeinfer import (I64, F64, BOOL, PF64, PI64, GPU_INTRINSICS,
                         MATH_FNS, MATH_MODULES)

MSLTY = {I64: "long", F64: "float", BOOL: "bool",
         PF64: "device float*", PI64: "device long*"}
SCALAR = {I64: "long", F64: "float", BOOL: "bool"}
INTRIN_ATTR = {"thread_id": "thread_position_in_threadgroup",
               "block_id": "threadgroup_position_in_grid",
               "block_dim": "threads_per_threadgroup"}

HEADER = """\
// Generated by hanajit (target="metal").
// NOTE: f64 arguments/locals are lowered to 32-bit float (Metal has no
// double); integer / and % use C truncation semantics on the GPU.
#include <metal_stdlib>
using namespace metal;

"""


class MSLGen:
    def __init__(self, func_ast, arg_types, var_types, ret_type):
        self.f = func_ast
        self.arg_types = arg_types
        self.var_types = var_types
        self.out = []
        self.depth = 1
        self.used_intrinsics = sorted(
            {n.func.id for n in ast.walk(func_ast)
             if isinstance(n, ast.Call) and isinstance(n.func, ast.Name)
             and n.func.id in GPU_INTRINSICS})

    def line(self, s):
        self.out.append("    " * self.depth + s)

    def generate(self):
        params = []
        for i, a in enumerate(self.f.args.args):
            ty = self.arg_types[a.arg]
            if ty in (PF64, PI64):
                params.append(f"{MSLTY[ty]} {a.arg} [[buffer({i})]]")
            else:
                params.append(f"constant {SCALAR[ty]}& {a.arg} "
                              f"[[buffer({i})]]")
        for name in self.used_intrinsics:
            params.append(f"uint _{name} [[{INTRIN_ATTR[name]}]]")
        sig = (f"kernel void {self.f.name}(\n        "
               + ",\n        ".join(params) + ")")

        # declare locals (params excluded) up front
        for name, ty in sorted(self.var_types.items()):
            if name in self.arg_types:
                continue
            zero = "false" if ty == BOOL else ("0.0f" if ty == F64 else "0")
            self.line(f"{SCALAR[ty]} {name} = {zero};")
        for stmt in self.f.body:
            self.stmt(stmt)
        body = "\n".join(self.out)
        return HEADER + sig + " {\n" + body + "\n}\n"

    # ------------------------------ statements ------------------------------
    def stmt(self, node):
        m = getattr(self, "s_" + type(node).__name__, None)
        if m is None:
            raise UnsupportedError(
                f"metal: unsupported statement {type(node).__name__}")
        m(node)

    def s_Assign(self, node):
        t = node.targets[0]
        if isinstance(t, ast.Subscript):
            self.line(f"{self.expr(t.value)}[{self.expr(t.slice)}] = "
                      f"{self.expr(node.value)};")
        else:
            self.line(f"{t.id} = {self.expr(node.value)};")

    def s_AugAssign(self, node):
        op = {ast.Add: "+", ast.Sub: "-", ast.Mult: "*", ast.Div: "/",
              ast.Mod: "%", ast.FloorDiv: "/", ast.BitAnd: "&",
              ast.BitOr: "|", ast.BitXor: "^", ast.LShift: "<<",
              ast.RShift: ">>"}.get(type(node.op))
        if op is None:
            raise UnsupportedError("metal: unsupported augmented op")
        self.line(f"{node.target.id} {op}= {self.expr(node.value)};")

    def s_Return(self, node):
        self.line("return;")  # Metal kernels are void; value is dropped

    def s_Expr(self, node):
        pass

    def s_Pass(self, node):
        pass

    def s_Break(self, node):
        self.line("break;")

    def s_Continue(self, node):
        self.line("continue;")

    def s_If(self, node):
        self.line(f"if ({self.expr(node.test)}) {{")
        self.depth += 1
        for s in node.body:
            self.stmt(s)
        self.depth -= 1
        if node.orelse:
            self.line("} else {")
            self.depth += 1
            for s in node.orelse:
                self.stmt(s)
            self.depth -= 1
        self.line("}")

    def s_While(self, node):
        self.line(f"while ({self.expr(node.test)}) {{")
        self.depth += 1
        for s in node.body:
            self.stmt(s)
        self.depth -= 1
        self.line("}")

    def s_For(self, node):
        v = node.target.id
        a = [self.expr(x) for x in node.iter.args]
        if len(a) == 1:
            start, stop, step = "0", a[0], "1"
        elif len(a) == 2:
            start, stop, step = a[0], a[1], "1"
        else:
            start, stop, step = a
        cond = (f"({step}) > 0 ? ({v} < ({stop})) : ({v} > ({stop}))"
                if step not in ("1",) else f"{v} < ({stop})")
        self.line(f"for ({v} = {start}; {cond}; {v} += {step}) {{")
        self.depth += 1
        for s in node.body:
            self.stmt(s)
        self.depth -= 1
        self.line("}")

    # ----------------------------- expressions ------------------------------
    def expr(self, node):
        if isinstance(node, ast.Constant):
            if isinstance(node.value, bool):
                return "true" if node.value else "false"
            if isinstance(node.value, float):
                return f"{node.value!r}f"
            return str(node.value)
        if isinstance(node, ast.Name):
            return node.id
        if isinstance(node, ast.Subscript):
            return f"{self.expr(node.value)}[{self.expr(node.slice)}]"
        if isinstance(node, ast.UnaryOp):
            op = {ast.USub: "-", ast.UAdd: "+", ast.Not: "!"}[type(node.op)]
            return f"({op}{self.expr(node.operand)})"
        if isinstance(node, ast.BinOp):
            if isinstance(node.op, ast.Div):
                return (f"((float)({self.expr(node.left)}) / "
                        f"(float)({self.expr(node.right)}))")
            if isinstance(node.op, ast.Pow):
                return (f"pow((float)({self.expr(node.left)}), "
                        f"(float)({self.expr(node.right)}))")
            op = {ast.Add: "+", ast.Sub: "-", ast.Mult: "*",
                  ast.FloorDiv: "/", ast.Mod: "%", ast.BitAnd: "&",
                  ast.BitOr: "|", ast.BitXor: "^", ast.LShift: "<<",
                  ast.RShift: ">>"}.get(type(node.op))
            if op is None:
                raise UnsupportedError("metal: unsupported operator")
            return f"({self.expr(node.left)} {op} {self.expr(node.right)})"
        if isinstance(node, ast.Compare):
            op = {ast.Eq: "==", ast.NotEq: "!=", ast.Lt: "<", ast.LtE: "<=",
                  ast.Gt: ">", ast.GtE: ">="}[type(node.ops[0])]
            return (f"({self.expr(node.left)} {op} "
                    f"{self.expr(node.comparators[0])})")
        if isinstance(node, ast.BoolOp):
            op = " && " if isinstance(node.op, ast.And) else " || "
            return "(" + op.join(self.expr(v) for v in node.values) + ")"
        if isinstance(node, ast.IfExp):
            return (f"({self.expr(node.test)} ? {self.expr(node.body)} : "
                    f"{self.expr(node.orelse)})")
        if (isinstance(node, ast.Call) and isinstance(node.func, ast.Attribute)
                and isinstance(node.func.value, ast.Name)
                and node.func.value.id in MATH_MODULES
                and node.func.attr in MATH_FNS):
            name = {"fabs": "abs"}.get(node.func.attr, node.func.attr)
            inner = ", ".join(f"(float)({self.expr(a)})" for a in node.args)
            return f"{name}({inner})"
        if isinstance(node, ast.Call) and isinstance(node.func, ast.Name):
            fn = node.func.id
            if fn in GPU_INTRINSICS:
                return f"(long)_{fn}"
            if fn == "abs":
                return f"abs({self.expr(node.args[0])})"
            if fn == "float":
                return f"(float)({self.expr(node.args[0])})"
            if fn == "int":
                return f"(long)({self.expr(node.args[0])})"
        raise UnsupportedError(
            f"metal: unsupported expression {type(node).__name__}")


def transpile(func_ast, arg_types, var_types, ret_type):
    return MSLGen(func_ast, arg_types, var_types, ret_type).generate()
