"""WebAssembly backend (experimental): retarget the LLVM module to wasm.

The same LLVM IR the CPU backend JITs is retargeted to wasm32/wasm64 and
emitted as WebAssembly assembly through llvmlite's WebAssembly target
(present in llvmlite >= 0.44 prebuilt wheels). llvmlite cannot emit a
linked .wasm binary itself — `emit_object` crashes on the wasm target in
current llvmlite builds, and a relocatable object would still need
wasm-ld — so `export_wasm` writes everything an external clang needs to
produce the final module, and runs clang automatically when one is on
PATH (clang compiles .ll directly and drives wasm-ld itself):

    <prefix>.ll         retargeted LLVM IR (input to clang)
    <prefix>.s          WebAssembly assembly (inspection; llvm-mc input)
    <prefix>.mjs        ES-module loader with libm->Math imports
    <prefix>.build.sh   the exact clang link command
    <prefix>.wasm       final module, only if clang was found

JS boundary notes (also stated in the generated loader): i64 maps to
BigInt, f64/bool to Number, and pointer arguments are byte offsets into
the instance's exported linear memory.
"""
import os
import shutil
import subprocess
import textwrap
from collections import namedtuple

TARGETS = {
    32: dict(triple="wasm32-unknown-unknown",
             datalayout="e-m:e-p:32:32-p10:8:8-p20:8:8-i64:64-"
                        "n32:64-S128-ni:1:10:20"),
    64: dict(triple="wasm64-unknown-unknown",
             datalayout="e-m:e-p:64:64-p10:8:8-p20:8:8-i64:64-"
                        "n32:64-S128-ni:1:10:20"),
}

# libm symbols the kernel may reference after target lowering (LLVM turns
# llvm.sin.f64 etc. into libcalls on wasm; sqrt/floor/ceil/fabs lower to
# native wasm instructions but are listed anyway — unused imports are
# simply ignored at instantiation).
JS_MATH_IMPORTS = [
    ("sqrt", "Math.sqrt"), ("exp", "Math.exp"), ("log", "Math.log"),
    ("sin", "Math.sin"), ("cos", "Math.cos"), ("tan", "Math.tan"),
    ("floor", "Math.floor"), ("ceil", "Math.ceil"), ("pow", "Math.pow"),
    ("fabs", "Math.abs"), ("atan2", "Math.atan2"),
]

WasmExport = namedtuple("WasmExport", "ll s mjs build wasm")


def retarget(module, bits=32):
    """Return the module's IR text with wasm triple/datalayout.

    The module object is restored afterwards, so retargeting a module the
    dispatcher still holds for inspection is safe.
    """
    cfg = TARGETS[bits]
    saved = (module.triple, module.data_layout)
    try:
        module.triple = cfg["triple"]
        module.data_layout = cfg["datalayout"]
        return str(module)
    finally:
        module.triple, module.data_layout = saved


def emit(module, func_name, bits=32):
    """Best-effort WebAssembly assembly emission. Returns (text, native).

    native=True: .s WebAssembly assembly from LLVM's wasm backend.
    native=False: retargeted IR text (offline clang/llc can finish the job).

    Emission runs in an isolated subprocess: llvmlite's wasm32 emitter
    access-violates on alloca-bearing modules, on some -O3 output shapes,
    and intermittently on repeated in-process emissions (observed with
    llvmlite 0.48 on Windows). `emit_object` is worse — it crashes
    outright — which is why the final .wasm link goes through clang.
    """
    ir_text = retarget(module, bits)
    from . import isolated
    text = isolated.emit_assembly(ir_text, TARGETS[bits]["triple"])
    if text is not None:
        return text, True
    return ir_text, False


def _link_flags(func_name, bits):
    """clang flags that turn <prefix>.ll into a runnable .wasm module."""
    return [f"--target={TARGETS[bits]['triple']}", "-O2", "-nostdlib",
            "-Wl,--no-entry", f"-Wl,--export={func_name}",
            "-Wl,--export-memory", "-Wl,--allow-undefined"]


def _loader(func_name, wasm_name, bits, sig=None, ret=None):
    imports = "\n".join(f"    {c}: {js}," for c, js in JS_MATH_IMPORTS)
    sig_note = ""
    if sig is not None:
        sig_note = (f"// signature: {func_name}({', '.join(sig)})"
                    + (f" -> {ret}" if ret else "") + "\n")
    return textwrap.dedent("""\
        // Generated by hanajit (export_wasm, wasm{bits}).
        {sig_note}\
        // JS boundary: i64 <-> BigInt, f64/bool <-> Number; pointer args
        // are byte offsets into the exported linear memory.
        //
        //     import {{ load }} from "./{stem}.mjs";
        //     const exports = await load();
        //     exports.{func_name}(...);

        const env = {{
        {imports}
        }};

        export async function load(source) {{
            source = source ?? new URL("./{wasm_name}", import.meta.url);
            let bytes;
            if (typeof source === "string" || source instanceof URL) {{
                const u = new URL(source, import.meta.url);
                if (u.protocol === "file:") {{
                    const {{ readFile }} = await import("node:fs/promises");
                    bytes = await readFile(u);
                }} else {{
                    bytes = await (await fetch(u)).arrayBuffer();
                }}
            }} else {{
                bytes = source;  // ArrayBuffer / Uint8Array
            }}
            const {{ instance }} = await WebAssembly.instantiate(
                bytes, {{ env }});
            return instance.exports;
        }}
        """).format(bits=bits, sig_note=sig_note, imports=imports,
                    func_name=func_name, wasm_name=wasm_name,
                    stem=os.path.splitext(os.path.basename(wasm_name))[0])


def export_wasm(module, func_name, path_prefix, bits=32, sig=None, ret=None):
    """Write WebAssembly artifacts next to `path_prefix`.

    Returns a WasmExport namedtuple of paths; `.s` is None if the wasm
    target is unavailable, `.wasm` is None unless clang linked it.
    """
    if bits not in TARGETS:
        raise ValueError(f"bits must be 32 or 64, got {bits!r}")
    ll_path = f"{path_prefix}.ll"
    s_path = f"{path_prefix}.s"
    mjs_path = f"{path_prefix}.mjs"
    build_path = f"{path_prefix}.build.sh"
    wasm_path = f"{path_prefix}.wasm"
    wasm_name = os.path.basename(wasm_path)

    with open(ll_path, "w", encoding="utf-8") as f:
        f.write(retarget(module, bits))
    text, native = emit(module, func_name, bits)
    if native:
        with open(s_path, "w", encoding="utf-8") as f:
            f.write(text)
    else:
        s_path = None
    with open(mjs_path, "w", encoding="utf-8") as f:
        f.write(_loader(func_name, wasm_name, bits, sig=sig, ret=ret))

    flags = _link_flags(func_name, bits)
    with open(build_path, "w", newline="\n") as f:
        f.write("#!/bin/sh\n"
                "# Link the retargeted IR into a runnable .wasm module.\n"
                "# Needs any clang with the WebAssembly backend "
                "(all standard builds).\n"
                + " ".join(["clang"] + flags
                           + ["-o", wasm_name, os.path.basename(ll_path)])
                + "\n")

    linked = None
    clang = os.environ.get("HANAJIT_WASM_CLANG") or shutil.which("clang")
    if clang:
        try:
            subprocess.run([clang] + flags + ["-o", wasm_path, ll_path],
                           check=True, capture_output=True, timeout=120)
            linked = wasm_path
        except Exception:
            linked = None  # build script documents the manual command
    return WasmExport(ll_path, s_path, mjs_path, build_path, linked)
